// Copyright (c) 2023, Adam Simpkins
#pragma once

#if !defined(ESP_TARGET)

// Use the config file generated by CMake on non-Espressif platforms
#include "ausb/ausb_config_vars.h"

#else // ESP_TARGET

// When building for Espressif chips, use their Kconfig configuration system.
#include "sdkconfig.h"

#define AUSB_CONFIG_HW_ESP CONFIG_AUSB_HW_ESP
#define AUSB_CONFIG_HW_MOCK CONFIG_AUSB_HW_MOCK

#endif // ESP_TARGET

// If AUSB_CONFIG_HW_MULTI was not explicitly forced on in the build
// configuration, automatically define it based on the number of supported
// hardware types.
#ifndef AUSB_CONFIG_HW_MULTI
#if AUSB_CONFIG_HW_MOCK + AUSB_CONFIG_HW_ESP > 1
#define AUSB_CONFIG_HW_MULTI 1
#else
#define AUSB_CONFIG_HW_MULTI 0
#endif
#endif
